# Generated by Django 5.2.8 on 2025-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem", models.CharField(max_length=64)),
                ("destino", models.CharField(max_length=64)),
                ("duracao", models.IntegerField()),
            ],
        ),
    ]
