# Generated by Django 5.2.8 on 2025-11-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aeroporto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=3)),
                ("cidade", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="voo",
            name="destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desembarques",
                to="voos.aeroporto",
            ),
        ),
        migrations.AlterField(
            model_name="voo",
            name="origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embarques",
                to="voos.aeroporto",
            ),
        ),
    ]
