# Generated by Django 5.2.8 on 2025-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voos", "0002_aeroporto_alter_voo_destino_alter_voo_origem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viajante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=64)),
                ("secondname", models.CharField(max_length=64)),
                (
                    "voos",
                    models.ManyToManyField(
                        blank=True, related_name="viajantes", to="voos.voo"
                    ),
                ),
            ],
        ),
    ]
